

services:
  mysql:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: prova
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: pino
      MYSQL_PASSWORD: prova
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  mysql-client:
    image: mysql:8.4
    entrypoint: ["sleep", "infinity"]
    networks:
      - app-network

  python-app:
    build:
      context: .
      dockerfile: Dockerfile.python
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: prova
    depends_on:
      - mysql
    ports:
      - "5000:5000"
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge

