# Usa l'immagine ufficiale di MySQL come base
FROM mysql:8.0

# Imposta le variabili d'ambiente per la configurazione di MySQL
ENV MYSQL_ROOT_PASSWORD=rootpassword
ENV MYSQL_DATABASE=mydatabase
ENV MYSQL_USER=myuser
ENV MYSQL_PASSWORD=mypassword

# Esponi la porta 3306 (la porta predefinita di MySQL)
EXPOSE 3306

# Comando per avviare MySQL
CMD ["mysqld"]